### ISSUE TITLE
Allow users to manage archival status of owned pits

### ISSUE THREAD

**Issue by cyrus01337** [DuckBot-Discord/duck-hideout-manager-bot#10]
Tracking issue.

### Things to do
- Ensure users can un-archive their pit by running `?unarchive` within it
- Give users the ability to control when it gets archived
    - This is similar to thread settings which can be used for inspiration

**Comment by LeoCx1000** [comment]
The command would be `-pit unarchive`, which already exists but would need modifications. And users should be able to un-archive their own pit from other channels, since pits that are archived aren't accessible.

---------------

Another thing, though I'm not sure about it quite yet, there should be a distinction from when a pit gets archived (by a user - to be added) / inactivity versus when it gets archived manually by a moderator. If the latter is the case then the user (if non-moderator) should not be able to un-archive it.

**Comment by irregularunit** [comment]
Based on the `schema.sql` provided, it seems that the desired functionality of unarchiving a pit can already be achieved without altering the table. 

These types already give us exactly what we need: `'leave', 'inactive', 'manual'`.
